apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrbenefitsagent
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: hr-benefits-agent-pod
  template:
    metadata:
      labels:
        pod: hr-benefits-agent-pod
    spec:
      containers:
      - name: hr-benefits-agent-container
        image: docker.io/starrparker/hrbenefitsagent:latest